const name=[
    "1. Abelisaurus",
    "2. Albertosaurus",
    "3. Allosaurus",
    "4. Ankylosaurus",
    "5. Apatosaurus",
    "6. Archaeopteryx",
    "7. Baryonyx",
    "8. Brachiosaurus",
    "10. Carnotaurus",
    "11. Coelophysis",
    "13. Deinonychus",
    "14. Diplodocus",
    "15. Edmontosaurus",
    "16. Giganotosaurus",
    "17. Gorgosaurus",
    "18. Iguanodon",
    "19. Leaellynasaura",
    "20. Megalosaurus",
    "21. Minmi",
    "22. Ornithomimus",
    "23. Parasaurolophus",
    "24. Protoceratops",
    "25. Spinosaurus",
    "26. Stegoceras",
    "27. Stegosaurus",
    "28. Suchomimus",
    "29. Triceratops",
    "30. Troodon",
    "31. Tyrannosaurus",
    "32. Velociraptor",

]
module.exports={name};