const  text=[
    
    "Abelisaurus is a theropod dinosaur, which existed during the late Cretaceous Era. It was predatory by nature. Unlike some other types of dinosaurs, Abelisaurus walked on two legs or was bipedal. The species was thought to be 7 to 9 meters in length and hence was considered a medium-sized dinosaur.How did the modern Era learn about Abelisaurus? Through a single skull that was found! And that too was incomplete. Through this skull, scientists were able to identify Abelisaurus’s diet, lifestyle and size.",
    "Have you heard of Tyrannosaurus? Well, our next dinosaur belongs to the same family.  Albertosaurus looks starkly similar to Tyrannosaurus. It too was a bipedal and had distinctively small arms. Considering its bone structure, the chances are that an Albertosaurus was a fast runner and might be one of the top species on the food chain. There is also evidence to suggest that the dinosaur might have had crests above their brightly coloured eyes. While Tyrannosaurus had eyes that pointed forwards, in case of Albertosaurus, its eyes were present on either side of its head.",
    "When you think of predators, Allosaurus is bound to come to mind. In the Jurassic Period, Allosaurus was one of the biggest predators treading the grounds of the Earth. It preyed on fellow species like Stegosaurus and Sauropods. As per evidence, its length might be around 12 meters. Its likely weight would be around 2 to 5 metric tonnes.",
    "Ankylosauria refers to a group of dinosaurs, each of which had similar bone structure. They each had armoured plates which were joined together. This is why they were called Ankylosauria or “fused lizards” in the first place. One dinosaur from this group is Ankylosaurus.Ankylosaurus had a length of approximately 10 metres and a weight of about five metric tonnes. The fact that the dinosaur had a club at the end of its tail made for an excellent weapon against any potential predators that might be out for its life.",
    "Apatosaurus existed in the late Jurassic Era and was a large sauropod species. Its weight was between 20 to 30 metric tonnes, while its length was approximately 20 to 23 metresRather than preying on other animals and dinosaurs, one of the largest dinosaurs of its time feasted on plants. To ensure its survival, it relied on its long tail to protect itself when need be.When Brontosaurus was first discovered, it was thought to belong to a different species altogether. However, soon, it was discovered that the two dinosaurs were, in fact, the same. Still, a lot of people continue to use the name Brontosaurus to refer to a separate kind of dinosaurs. And now recent studies have begun to show that Brontosaurus might have been a different dinosaur all along!",
    "Archaeopteryx was midway between a bird and a small dinosaur, Its mouth was full of teeth, and its tail was quite bony. It was covered in features. However, it couldn’t fly but could glide. It lived during the Jurassic period, and animals like it might have been the ancestors of modern birds.",
    "Back in 1983, William J. Walker, who was then a beginner fossil collector, stumbled on a unique fossil. When he showed his finding to the Natural History Museum in London, they discovered that Walker had discovered something exemplary! He had found over three-quarters of a dinosaur that was never heard before. The dinosaur then went on to be known as Baryonyx walkeri. This was a tribute to its discoverer. The dinosaur was bipedal and devoured fishes rather than plants or animals.",
    "Dinosaurs were huge in general. You can imagine what the largest dinosaur would look like! That is what Brachiosaurus was. This sauropod has a length of approximately 25 meters and a weight of 30-50 metric tonnes. Considering the unique way, the forelimb of the dinosaur met its shoulder, the scientist coined its name Brachiosaurus, or “arm-lizard”. While other sauropods had front legs that were shorter than their hind legs, the opposite was true for this species.",
    "As mentioned before, Brontosaurus generally refers to Apatosaurus even though there has been recent evidence to suggest otherwise.",
    "Three things distinctively describe a Carnotaurus. Large size with two horns adorned on its head. Exceptionally fast predator. Bipedal. The dinosaur had a weight of 1.35 metric tonnes and a length of 9 meters. This species of dinosaurs ate meat and earned itself the name “meat-eating” bull because of its unique horns.",
    "As per current evidence, Coelophysis is one of the oldest dinosaurs. It existed back in the Triassic Era. Even though they are the earliest dinosaurs to be found, their fossil fuels have remained intact enough to give insights to scientists. As per the findings of the fossil fuel discovered, this dinosaur was likely quite small and fast. It is believed that they hunted as part of a group rather than alone.",
    "As of now, two specimens belonging to Compsognathus have been found. While the first was discovered in the mid-19th century in Germany, the other was found in 1971, all the way in France. It is believed that this dinosaur lives in the late Jurassic Era. It has quite a bird-like bone structure and walked on two legs. For the longest time, it was believed to be the smaller dinosaur that lived. However, since the 12th century, various other small dinosaurs’ fossil fuels have been unearthed.",
    "Deinonychus was active during the Cretaceous time. It features a small size, with a length of three meters and a weight of 80 kg. One of its distinctive characteristics is its claw which can be deadly if used on someone. These claws are present on both feet. Compared to other small dinosaurs, Deinonychus is likely to be faster. Its long forelimbs along with clawed hands made it an excellent predator.",
    "Diplodocus was a sauropod. And just like other dinosaurs in this category, Diplodocus too was massive. It walked on four legs and featured an abnormally long tail and neck. This tail might have been used to protect itself from potential predators. Its length was approximately 25 meters, and its weight was between 10-26 metric tonnes. It lived in the late Jurassic Period and trod the grounds of North America predominately.",
    "Edmontosaurus majorly was present in North America during the Cretaceous period. This herbivorous species was one of the many types of “duck-billed” dinosaurs of its age. It came under this category because of its mouth which reflected the shape of a duck’s mouth.Even through grazers tend to walk on four legs, palaeontologists believe that Edmontosaurus likely walked on its two long hind legs.",
    "The fact that it has the word “giant” in its name is enough to tell you what kind of a dinosaur Giganotosaurus was. This species was a bipedal dinosaur which featured a length and height which was significantly bigger than the might Tyrannosaurus. With a length of 16 meters and a weight of 8 metric tonnes, this predator was a giant for sure. It is also believed that it has an excellent sense of smell and sight, making it a dangerous predator. Giganotosaurus trod the grounds of South America back in the late Cretaceous Period.",
    "Gorgosaurus means dreadful lizard. If you have seen its fossil fuel, you will know why. Gorgosaurus features a massive skull, and its jaws were full of sharp teeth. The species existed in the late Cretaceous Period in Canada and America and belonged to the same family as Tyrannosaurus. This family of dinosaurs are largely known as Tyrannosauridae.",
    "Iguanodon has the distinction of being the second dinosaur to be discovered and named. The first fossil that was unearthed of the species was its tooth. The wife of geologist and medical doctor Dr Gideon Mantell stumbled upon the fossil and decided to call it Iguanodon. Why? Because, to them, the tooth resembled the shape of an iguanaThis herbivorous dinosaur was quite large and could walk on both two and four legs. It was a product of the early times during the Cretaceous Period. The dinosaur noticeably had spiked thumbs. It is believed that these thumbs were used as defence weapons to keep predators at bay.",
    "Leaellynasaura existed during the early days of the Cretaceous Period. The dinosaur walked on two legs and might have been covered in features. Its size was very small, with a length of 1 meter. Its remains were unearthed in Dinosaur Cove, which is situated in Australia.",
    "We told you about the second dinosaur that was named by humans. You might be wondering which was the first. Well, it was none other than Megalosaurus, whose remains were found in England. James Parkinson, a surgeon and geologist by profession, found it and named it in 1824. This was before we knew dinosaur existed! The species was 9 meters long and one metric tonne in weight. It was bipedal and a predator who thrived in the mid-Jurassic Era.",
    "Minmi belonged to the Ankylosauria category of dinosaurs. It was small in size yet was heavily armoured due to its bony plate coverage over the entire body. Such plates were also found on its underside. Compared to other dinosaurs in the Ankylosauria category, Minmi had longer legs suggesting it might have been able to move quickly regardless of its armoured body. The species existed during the early days of the Cretaceous Period, and its remains were found in Australia.",
    "Ornithomimus resembled an ostrich. Except that unlike an ostrich, it was around 11.5 feet long and had a speed of 40 mph. Its long and thin neck along with its feet earned it the name Ornithomimus, or “bird mimic”. There is also evidence to suggest the dinosaur might have had feathers.",
    "Parasaurolophus lived in the late years of the Cretaceous period. It was a herbivore with a length of 10 meters and a weight of 3.5 metric tonnes. Its distinctive feature was the crest present at the back of its head, whose tube was linked to its nostrils. As per scientist, this structure might have allowed a Parasaurolophus to produce sound effectively. It also had a long and narrow tail, which might have been brightly coloured.",
    "During the late Cretaceous Period, sheep-sized dinosaur existed. It was called Protoceratops. Its jaw was shaped similar to a parrot’s bill while it had a lot of teeth to ensure easy chewing of vegetation. It had a frill on its back, possibly to keep its neck protectedIts fossil was found in Mongolia and was wrapped in a velociraptor fossil. It is speculated that the herbivore might have been attacked before both species were buried in a landslip.",
    "This meat-eating dinosaur had a length of 15 meters, a weight of 23 metric tonnes and lived during the Cretaceous Period. As per recent discoveries, Spinosaurus continues to be the largest meat-eating dinosaurThe animal had a “sail” on its back which referred to a layer of prominent spine covered by skin. This might have played a role in giving it agility that could have been used for hunting.",
    "This bipedal dinosaur was a herbivore that walked the Earth in the late years of the Cretaceous Period in North America. It was 2.5 feet tall and 2 meters long.",
    "It had a prominently thick skull and might have lived as part of herds.",
    "Stegosaurus belonged to the Stegosauridae group and was a herbivore. It lived in America in the late parts of the Jurassic Period. A fully grown Stegosaurus had a length of 9 meters and a weight of 2 metric tonnes. The best part about this dinosaur is its brain, which had the same size as a walnutOn the upper part of its back, a Stegosaurus had large bony plates which might be present to maintain body temperature or protect against attacks. The latter was also achieved by the presence of spikes on Stegosaurus’s tailA popular member of the Spinosauridae family, Suchomimus has quite a lot of similarity with its family member, Spinosaurus. It too has a sail on its back and features a crocodile-like, long face. It existed in the Cretaceous Period in the lands of Africa.",
    "Triceratops is a herbivore that surely didn’t look the part. Instead, this large dinosaur was very heavily built and hence was capable of fighting off predators. Evidence suggests that it lived as part of herds.",
    "This dinosaur looked quite like a bird. It was small, with a length of 2 meters. Its height would come at the waist of an average sized man. Even with its small size, it was ready to fight off any predators. This was ensured by its pointy teeth, clawed feet and finger. It had good eyesight and was very fast.",
    "The chances are you have heard of Tyrannosaurus. Tyrannosaurus Rex is popular among the masses as being the “killer” species. It is one of the largest predators that have lived on Earth. Its strength was matched by its intelligence and quick senses. A key feature of a Tyrannosaurus was its massive skull that managed to support its equally massive jaw muscle. This gave the Tyrannosaurus a very strong bite. It had a length of 12 meters and a weight of 8 metric tonnes and lived during the late Cretaceous Period.",
    "This predator also lived during the ending days of the Cretaceous Period. Its small size and bird-like features aided it in becoming a fast and strong meat-eater. It had pointy teeth along with sharp claws. Each of its foot featured a curved claw that helped it in grabbing and killing off its prey with ease.",


]

module.exports={text};